[package]
name = "rdzawa_bestia"
version = "0.1.0"
edition = "2021"


[dependencies]
arrayvec = "0.7.4"
rand = "0.8.5"
chess = "3.2.0"
json = "0.12.4"
test-case = "3.3.1"
tch = "0.18.0"

#[profile.release]
#debug = true